cp default debug keystore file
aerogear/digger-android-slave-image pull request #9
Opened 2018-05-07 13:23 UTC by odra

default keystore + ruby/fastlane fix

2018-05-07 13:41 UTC, matskiv commented on Dockerfile
> +gem install fastlane -v ${FASTLANE_DEFAULT_VERSION} && \
let's install it without documentation for efficiency:
`gem install --no-rdoc --no-ri ...`

2018-05-09 08:01 UTC, ghost approved these changes

2018-05-09 08:05 UTC, ghost requested changes

2018-05-09 08:05 UTC, vchepeli commented on Dockerfile
> +RUN wget https://rvm.io/binaries/centos/7/x86_64/ruby-2.4.2.tar.bz2 && \
Versions better to pass as arguments 
```sh
ARG RUBY_VERSION=2.4.2
ARG JAVA_VERSION=1.8.0
```

2018-05-09 10:26 UTC, ghost approved these changes

2018-05-09 11:04 UTC, merged